// src/components/Prettier/Timeline/TimelinePeriodDetails.svelte
<script type="ts">
    export let details: string[] | string;
</script>

{#if Array.isArray(details)}
    <div class="detail">
        <ul>
            {#each details as item}
                <li>{item}</li>
            {/each}
        </ul>
    </div>
{:else}
    <div class="detail">{details.toString()}</div>
{/if}

<style lang="scss">
  @import "./variables";

  .detail {
    margin-bottom: $gap;
    ul {
      padding-left: 2em;
    }
  }
</style>

// components/Prettier/Timeline/TimelinePeriodDetails.tsx
import React from "react";
import style from "./TimelinePeriodDetails.module.scss";

interface ITimelinePeriodDetailsProps {
    details: string[] | string;
}

export default class TimelinePeriodDetails extends React.Component<ITimelinePeriodDetailsProps> {
    render() {
        if (Array.isArray(this.props.details)) {
            return (
                <div className={style.detail}>
                    <ul>
                        {this.props.details.map((item) => (
                            <li key={item}>{item}</li>
                        ))}
                    </ul>
                </div>
            )
        }
        return <div className={style.detail}>{this.props.details.toString()}</div>
    }
}
